# Everytime we use docker, we need super user permission
language: generic
sudo: required
services:
  # Create a copy of docker on backend
  - docker

# Contains series of actions before our test starts
before_install:
  # Command to build docker image
  - docker build -t coldperformer/docker-react -f Dockerfile.dev .

# All the commands that needs to be executed to actually run tests
scripts:
  - docker run -e CI=true coldperformer/docker-react npm run test

# To deploy settings
deploy:
  provider: elasticbeanstalk
  # Present in URL
  region: "us-east-2"
  # Name of the app
  app: "docker"
  # Name of the environment
  env: Docker-env
  # Present in S3 services on AWS
  bucket_name: "elasticbeanstalk-us-east-2-005290685595"
  # Folder inside S3 services that contains the environment
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY